管理员部分以及新生查询部分基本完成
1604104se-hitwh/welcome pull request #19
Opened 2019-04-12 12:44 UTC by specialpointcentral

- 基本实现管理员对新生信息的管理
- 基本实现新生信息查询

2019-04-12 12:51 UTC, specialpointcentral commented
提出修改，之后再合并dev

2019-04-12 12:56 UTC, specialpointcentral commented
`enrollInfo.blade.php`需要修改
@cn-chenium @KashingLiu

2019-04-12 13:59 UTC, zuksan requested changes
enrollInfo.blade.php的352行到367行似乎有些问题

2019-04-12 14:28 UTC, specialpointcentral commented
问题情况：
- [问题1](https://app.codacy.com/app/specialpointcentral/welcome/file/33625658074/issues/source?bid=12203353&fileBranchId=12294176)
- [问题2](https://app.codacy.com/app/specialpointcentral/welcome/file/33625658114/issues/source?bid=12203353&fileBranchId=12294176)

需要更改后再做提交。

具体步骤：
1.  获取远端分支
```git
git remote update origin -p
```

2. 确认远程分支正确
```git
git branch -a
```

3. 克隆远端dev分支，并切换到dev
```git
git checkout dev
```
如果此时你是dev分支，建议执行：
```git
git checkout -b xxxdev
git branch -d dev
git checkout dev
```

4. 开xxxfix分支进行修复
```git
git checkout -b xxxfix
```

5. 完成修复提交到github
```git
git push origin xxxfix
```

6. 发起pr
发送到`dev`的`pull request`
注意分支`dev`正处于等待`merge`状态， #19 

> **注意** 
> 此时一定不要做pr确认，一定要等自动构建和检查工具完成并确认无误（出现绿勾），才能决定是否进行`merge`。
> 建议还要进行队内的代码检查。可以在`Reviewers`里面设置。
> 正在检查的会显示黄点，通过的是绿勾，不通过的会出现红叉。
> 
> **所有的红叉都要仔细查看**

7. 进行`merge`，完成一次pr

8. 删除此分支，此时pr系统会提示你删除

9. 对本地的分支进行修剪
```git
git remote update origin -p
```

10. 删除本地不需要的分支

2019-04-14 01:14 UTC, zuksan approved these changes

2019-04-14 02:52 UTC, merged